# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value



services:
    hello_service:
        class: AppBundle\Services\HelloService
        arguments: ['@mailer']
    
    

