controlador_index:
    path: /usuarios/index
    defaults: {_controller: AppBundle:Usuarios:index}
    
controlador_addPerfil:
    path: /perfiles/addPerfil
    defaults: {_controller: AppBundle:perfiles:addPerfil}

controlador_readPerfil:
    path: /perfiles/readPerfil
    defaults: {_controller: AppBundle:perfiles:readPerfil}
    
controlador_delPerfil:
    path: /perfiles/delPerfil/{id}
    defaults: {_controller: AppBundle:perfiles:delPerfil}
    
controlador_addModulo:
    path: /modulos/addModulo
    defaults: {_controller: AppBundle:Modulos:addModulo}
    
controlador_readModulo:
    path: /modulos/readModulo
    defaults: {_controller: AppBundle:Modulos:readModulo}

controlador_delModulo:
    path: /modulos/delModulo/{id}
    defaults: {_controller: AppBundle:Modulos:delModulo}
    
controlador_addPerfilMOD:
    path: /perfilesMOD/addPerfilMOD/{idPerfil}/{idModulo}
    defaults: {_controller: AppBundle:perfilesMOD:addPerfilMOD, idPerfil:GER,idModulo:MUS}
    
controlador_addUsuario:
    path: /usuarios/addUsuario
    defaults: {_controller: AppBundle:Usuarios:addUsuario}
    
controlador_readUsuario:
    path: /usuarios/readUsuario
    defaults: {_controller: AppBundle:Usuarios:readUsuario}
    
controlador_delUsuario:
    path: /usuarios/delUsuario/{id}
    defaults: {_controller: AppBundle:Usuarios:delUsuario}
    
controlador_updateUsuario:
    path: /usuarios/updateUsuario
    defaults: {_controller: AppBundle:Usuarios:updateUsuario}
    
controlador_loginAction:
    path: /usuarios/login/{login}/{password}
    defaults: {_controller: AppBundle:Usuarios:login, login:admin,password:admin}
    
controlador_soap:
    path: /soap
    defaults: {_controller: AppBundle:HelloService:index}